# Variables
export DOTFILES="$HOME/.dotfiles"

# Aliases

# Paths 
typeset -U path

path=(
  "$N_PREFIX/bin"
  $path
  "/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
)

# Functions
function mkcd() {
  mkdir -p "$@" && cd "$_";
}

# Load "New" Completion System
autoload -Uz compinit && compinit
