#!/usr/bin/env zsh

##  '########::'######::'##::::'##:'########:::'######::
##  ..... ##::'##... ##: ##:::: ##: ##.... ##:'##... ##:
##  :::: ##::: ##:::..:: ##:::: ##: ##:::: ##: ##:::..::
##  ::: ##::::. ######:: #########: ########:: ##:::::::
##  :: ##::::::..... ##: ##.... ##: ##.. ##::: ##:::::::
##  : ##::::::'##::: ##: ##:::: ##: ##::. ##:: ##::: ##:
##   ########:. ######:: ##:::: ##: ##:::. ##:. ######::
##  ........:::......:::..:::::..::..:::::..:::......:::
##  ####################################################

# Variables
export DOTFILES=$HOME/.dotfiles
export VARIABLE_ZSH=$DOTFILES/source/zsh/variable.zsh
. $VARIABLE_ZSH

# Oh My ZSH
ZSH_THEME="dracula"

plugins=(
  git
  zsh-syntax-highlighting
  zsh-autosuggestions
)

. $ZSH_SH
. $ZSH_SYNTAX_HIGHLIGHTING
. $COLORLS

# Adjust History Variables & Options
unsetopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt HIST_NO_STORE
setopt EXTENDED_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FIND_NO_DUPS
setopt AUTO_CD
setopt GLOB_DOTS
setopt EXTENDED_GLOB
setopt NO_HUP
setopt NOTIFY
setopt CORRECT

# Aliases
. $ALIAS_ZSH

# Paths
. $PATH_ZSH

# Functions
. $FUNCTION_ZSH

# Plugins
ZSH_AUTOSUGGEST_STRATEGY=(history completion)

# Load "New" Completion System
zstyle ':completion:*:*:*:*:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
zstyle ':plugin:history-search-multi-word' clear-on-cancel 'yes'
autoload -Uz compinit && compinit

# prompt(s)
eval "$(starship init zsh)"

eval $(thefuck --alias)

[ -f ~/.fzf.zsh ] && . ~/.fzf.zsh
